# Пользователь

## Получить текущего пользователя

GET http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmMwY2EwNzgxNzE2NjcxODBlMTUxYiIsImVtYWlsIjoicGF2ZWxsYm9yMTlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJwYXZlbDE5IiwiaWF0IjoxNzExMjkxODQ4LCJleHAiOjE3MTE0NjQ2NDh9.uLqRYU3evh4lLS3X-Ct_nBYInLztHppMkrGIe-E565s

###

## Обновить пользователя

PATCH  http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmMwY2EwNzgxNzE2NjcxODBlMTUxYiIsImVtYWlsIjoicGF2ZWxsYm9yMTlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJncnUyIiwiaWF0IjoxNzExNDY1NTM1LCJleHAiOjE3MTE2MzgzMzV9.HQF8kDBn3sOnL13qmiHRuU_kfcw3wcYHlxNQ9cpApL0
Content-Type: application/json

{
  "user": {
    "email": "gru4@gru.ru",
    "bio": "Lover1"
  }
}

###

## Загрузить аватар

POST  http://localhost:3000/user/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmMwY2EwNzgxNzE2NjcxODBlMTUxYiIsImVtYWlsIjoicGF2ZWxsYm9yMTlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJwYXZlbDE5IiwiaWF0IjoxNzExMjkxODQ4LCJleHAiOjE3MTE0NjQ2NDh9.uLqRYU3evh4lLS3X-Ct_nBYInLztHppMkrGIe-E565s
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Подпись Павел.png"
Content-Type: image/png

< C:\Users\Mgfck\Pictures\Подпись Павел.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###