# Пользователи

## Получить список пользователей

GET  http://localhost:3000/users HTTP/1.1

###

## Авторизовать пользователя

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "sublezub@ya.ru",
    "password": "qwerty123"
  }
}

###

## Создать нового пользователя

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "user": {
    "username": "sublezub123",
    "email": "sublezu132b@ya.ru",
    "password": "qwerty123"
  }
}

###

## Удалить пользователя

GET  http://localhost:3000/users HTTP/1.1

###
